### ISSUE TITLE
Activer l'envoi de mail

### ISSUE THREAD

**Issue by VincentFarcy** [data-players/Opaline#10]

**Comment by simonLouvet** [comment]
Coucou @VincentFarcy , peux tu préciser un peut ce qu'est l'envoie de mail. Je souhaite passer par mailjet pour faciliter la maintenance. dispo pour la mise en place technique.

**Comment by VincentFarcy** [comment]
dans l'appli il y a un formulaire de contact.
Il est accessible par programme ou depuis le menu pour contacter collectif emploi

**Comment by simonLouvet** [comment]
merci du rafraîchissement de mémoire. Le serveur doit donc passer par smtp pour envoyer un mail. C'est la que j'aimerai systématiser l'utilisation d'outil comme mailjet pour la maintenance.

**Comment by simonLouvet** [comment]
Je ne connais de plateforme open-source qui font a même chose : Template de mail + déclenchement d'envoie par API.

**Comment by VincentFarcy** [comment]
J'ai refait le test d'envoi d'email dans insomnia (ok)

Puis avec le code JS généré, j'ai fait un test d'envoi de mail depuis le frontend : 
![image](https://user-images.githubusercontent.com/55813208/157119404-7c761ab0-28ec-4a48-93ba-80eb26660fe6.png)

En ajoutant mode:"no-cors" : 
![image](https://user-images.githubusercontent.com/55813208/157119516-34809328-c64c-4aa3-a540-3e7ef0f077e9.png)

De ce que je comprend de la doc et de stackoverflow, il faut passer par le backend : 
https://dev.mailjet.com/email/guides/getting-started/
https://stackoverflow.com/questions/58734781/can-i-make-a-mailjet-api-call-using-fetch
https://stackoverflow.com/questions/29939361/couldnt-get-rid-of-the-multi-origins-error-when-sending-an-ajax-request-to-mail

**Comment by simonLouvet** [comment]
@VincentFarcy effectivement et c'est logique pour préserver la sécurité de la clef d'api
