### ISSUE TITLE
Backoffice : Personne à contacter : personne est rattachée à une structure 

### ISSUE THREAD

**Issue by alicetatangwidjaja** [data-players/Opaline#32]
Personne à contacter -> devrait être rattachée à un programme (pas à une structure)

**Comment by simonLouvet** [comment]
besoin de clarifier le besoin

**Comment by alicetatangwidjaja** [comment]
@simonLouvet  je ne suis pas sûre de ce besoin, alors on laisse dans le backlog ou on le supprime. Car je vois dans le backoffice dans la section Programme, il est bien possible de rattacher une personne à contacter à un programme. Du coup c'est suffisant.
